import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import type { Metadata } from "next";
import NavLink from "../components/NavButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900`}>
        <nav>
          <NavLink text="Jobs" />
          <NavLink url="contact" text="Contact" />
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
